services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.truffleganche
    ports:
      - 8545:8545
    volumes:
      - ./src/contracts:/app/src/contracts
    networks:
      - app-network

  frontend:
    build: .
    ports:
      - 80:3000
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./src/contracts:/app/src/contracts
networks:
  app-network: